---
name: Wire-Pod
version: 1.0
slug: wire-pod
description: Docker Ubuntu base for WirePod
url: https://github.com/hassio-addons/addon-ubuntu-base
webui: http://[HOST]:[PORT:8080]
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
uart: true
ports:
  443/tcp: 443
  80/tcp: 80
  8080/tcp: 8080